-- CreateTable
CREATE TABLE "PaymentConfig" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'payment-config',
    "pagarmeEnabled" BOOLEAN NOT NULL DEFAULT false,
    "pagarmeApiKey" TEXT,
    "pagarmeEncryptionKey" TEXT,
    "asaasEnabled" BOOLEAN NOT NULL DEFAULT false,
    "asaasApiKey" TEXT,
    "asaasWalletId" TEXT,
    "manualPixEnabled" BOOLEAN NOT NULL DEFAULT false,
    "pixKey" TEXT,
    "pixHolder" TEXT,
    "pixBank" TEXT,
    "maxInstallments" INTEGER NOT NULL DEFAULT 12,
    "minInstallmentValue" DECIMAL NOT NULL DEFAULT 5.00,
    "interestRate" DECIMAL NOT NULL DEFAULT 0.00,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_StoreConfig" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'store-config',
    "storeName" TEXT NOT NULL DEFAULT 'Gut Cosméticos & Makes',
    "description" TEXT,
    "bannerUrl" TEXT,
    "logoUrl" TEXT,
    "cnpj" TEXT,
    "legalName" TEXT,
    "themeColor" TEXT NOT NULL DEFAULT '#db2777',
    "accentColor" TEXT NOT NULL DEFAULT '#db2777',
    "priceColor" TEXT NOT NULL DEFAULT '#db2777',
    "secondaryColor" TEXT NOT NULL DEFAULT '#fce7f3',
    "backgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "menuColor" TEXT NOT NULL DEFAULT '#334155',
    "menuFont" TEXT NOT NULL DEFAULT 'Inter',
    "menuFontSize" TEXT NOT NULL DEFAULT '14px',
    "headerColor" TEXT NOT NULL DEFAULT '#ffffff',
    "cartCountBg" TEXT NOT NULL DEFAULT '#22c55e',
    "cartCountText" TEXT NOT NULL DEFAULT '#ffffff',
    "searchBtnBg" TEXT NOT NULL DEFAULT '#db2777',
    "searchIconColor" TEXT NOT NULL DEFAULT '#ffffff',
    "headingColor" TEXT NOT NULL DEFAULT '#111827',
    "sectionTitleColor" TEXT NOT NULL DEFAULT '#111827',
    "headingFont" TEXT NOT NULL DEFAULT 'Inter',
    "headingFontSize" TEXT NOT NULL DEFAULT '2rem',
    "headerBtnBg" TEXT NOT NULL DEFAULT '#db2777',
    "headerBtnText" TEXT NOT NULL DEFAULT '#ffffff',
    "productBtnBg" TEXT NOT NULL DEFAULT '#db2777',
    "productBtnText" TEXT NOT NULL DEFAULT '#ffffff',
    "bodyColor" TEXT NOT NULL DEFAULT '#334155',
    "bodyFont" TEXT NOT NULL DEFAULT 'Inter',
    "bodyFontSize" TEXT NOT NULL DEFAULT '1rem',
    "textColor" TEXT NOT NULL DEFAULT '#334155',
    "fontFamily" TEXT NOT NULL DEFAULT 'Inter',
    "instagram" TEXT,
    "instagramToken" TEXT,
    "facebook" TEXT,
    "youtube" TEXT,
    "tiktok" TEXT,
    "twitter" TEXT,
    "pinterest" TEXT,
    "pinterestTag" TEXT,
    "whatsapp" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "address" TEXT,
    "mapUrl" TEXT,
    "footerBg" TEXT NOT NULL DEFAULT '#171717',
    "footerText" TEXT NOT NULL DEFAULT '#a3a3a3',
    "footerLogo" BOOLEAN NOT NULL DEFAULT true,
    "newsletterEnabled" BOOLEAN NOT NULL DEFAULT true,
    "showPaymentMethods" BOOLEAN NOT NULL DEFAULT true,
    "showSocialIcons" BOOLEAN NOT NULL DEFAULT true,
    "categoryDefaultImage" TEXT,
    "mobileColumns" INTEGER NOT NULL DEFAULT 2,
    "desktopColumns" INTEGER NOT NULL DEFAULT 4,
    "paginationType" TEXT NOT NULL DEFAULT 'infinite',
    "showInstallments" BOOLEAN NOT NULL DEFAULT true,
    "enableQuickBuy" BOOLEAN NOT NULL DEFAULT true,
    "showColorVariations" BOOLEAN NOT NULL DEFAULT false,
    "showHoverImage" BOOLEAN NOT NULL DEFAULT true,
    "showCardCarousel" BOOLEAN NOT NULL DEFAULT false,
    "showLowStockWarning" BOOLEAN NOT NULL DEFAULT true,
    "showProductSold" BOOLEAN NOT NULL DEFAULT true,
    "showPromoPrice" BOOLEAN NOT NULL DEFAULT true,
    "showDiscountPayment" BOOLEAN NOT NULL DEFAULT true,
    "showInstallmentsDetail" BOOLEAN NOT NULL DEFAULT true,
    "showVariations" BOOLEAN NOT NULL DEFAULT true,
    "showMeasurements" BOOLEAN NOT NULL DEFAULT false,
    "showSKU" BOOLEAN NOT NULL DEFAULT true,
    "showStockQuantity" BOOLEAN NOT NULL DEFAULT true,
    "showShippingSimulator" BOOLEAN NOT NULL DEFAULT true,
    "showBuyInfo" BOOLEAN NOT NULL DEFAULT true,
    "showRelatedProducts" BOOLEAN NOT NULL DEFAULT true,
    "minPurchaseValue" DECIMAL NOT NULL DEFAULT 0.00,
    "enableQuickCart" BOOLEAN NOT NULL DEFAULT true,
    "cartAction" TEXT NOT NULL DEFAULT 'notification',
    "showCartRecommendations" BOOLEAN NOT NULL DEFAULT true,
    "showShippingCalculator" BOOLEAN NOT NULL DEFAULT true,
    "homeLayout" TEXT NOT NULL DEFAULT '[{"id":"hero","label":"Banners Rotativos","enabled":true},{"id":"new-arrivals","label":"Produtos Novos","enabled":true},{"id":"testimonials","label":"Depoimentos","enabled":true},{"id":"instagram","label":"Instagram","enabled":true}]',
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMessage" TEXT DEFAULT 'Estamos reformando a loja e está ficando incrível. Volte em alguns dias.',
    "maintenancePassword" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_StoreConfig" ("address", "backgroundColor", "bannerUrl", "bodyColor", "bodyFont", "bodyFontSize", "cartAction", "cartCountBg", "cartCountText", "categoryDefaultImage", "createdAt", "description", "desktopColumns", "email", "enableQuickBuy", "enableQuickCart", "facebook", "fontFamily", "footerBg", "footerLogo", "footerText", "headerColor", "headingColor", "headingFont", "headingFontSize", "homeLayout", "id", "instagram", "instagramToken", "logoUrl", "maintenanceMessage", "maintenanceMode", "maintenancePassword", "mapUrl", "menuColor", "menuFont", "menuFontSize", "minPurchaseValue", "mobileColumns", "newsletterEnabled", "paginationType", "phone", "pinterest", "pinterestTag", "searchBtnBg", "searchIconColor", "secondaryColor", "showBuyInfo", "showCardCarousel", "showCartRecommendations", "showColorVariations", "showDiscountPayment", "showHoverImage", "showInstallments", "showInstallmentsDetail", "showLowStockWarning", "showMeasurements", "showPaymentMethods", "showProductSold", "showPromoPrice", "showRelatedProducts", "showSKU", "showShippingCalculator", "showShippingSimulator", "showSocialIcons", "showStockQuantity", "showVariations", "storeName", "textColor", "themeColor", "tiktok", "twitter", "updatedAt", "whatsapp", "youtube") SELECT "address", "backgroundColor", "bannerUrl", "bodyColor", "bodyFont", "bodyFontSize", "cartAction", "cartCountBg", "cartCountText", "categoryDefaultImage", "createdAt", "description", "desktopColumns", "email", "enableQuickBuy", "enableQuickCart", "facebook", "fontFamily", "footerBg", "footerLogo", "footerText", "headerColor", "headingColor", "headingFont", "headingFontSize", "homeLayout", "id", "instagram", "instagramToken", "logoUrl", "maintenanceMessage", "maintenanceMode", "maintenancePassword", "mapUrl", "menuColor", "menuFont", "menuFontSize", "minPurchaseValue", "mobileColumns", "newsletterEnabled", "paginationType", "phone", "pinterest", "pinterestTag", "searchBtnBg", "searchIconColor", "secondaryColor", "showBuyInfo", "showCardCarousel", "showCartRecommendations", "showColorVariations", "showDiscountPayment", "showHoverImage", "showInstallments", "showInstallmentsDetail", "showLowStockWarning", "showMeasurements", "showPaymentMethods", "showProductSold", "showPromoPrice", "showRelatedProducts", "showSKU", "showShippingCalculator", "showShippingSimulator", "showSocialIcons", "showStockQuantity", "showVariations", "storeName", "textColor", "themeColor", "tiktok", "twitter", "updatedAt", "whatsapp", "youtube" FROM "StoreConfig";
DROP TABLE "StoreConfig";
ALTER TABLE "new_StoreConfig" RENAME TO "StoreConfig";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
